// Generated by gencpp from file ex2_pkg_msgs/joints.msg
// DO NOT EDIT!


#ifndef EX2_PKG_MSGS_MESSAGE_JOINTS_H
#define EX2_PKG_MSGS_MESSAGE_JOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ex2_pkg_msgs/position.h>

namespace ex2_pkg_msgs
{
template <class ContainerAllocator>
struct joints_
{
  typedef joints_<ContainerAllocator> Type;

  joints_()
    : positions()  {
    }
  joints_(const ContainerAllocator& _alloc)
    : positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ex2_pkg_msgs::position_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ex2_pkg_msgs::position_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::ex2_pkg_msgs::joints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ex2_pkg_msgs::joints_<ContainerAllocator> const> ConstPtr;

}; // struct joints_

typedef ::ex2_pkg_msgs::joints_<std::allocator<void> > joints;

typedef boost::shared_ptr< ::ex2_pkg_msgs::joints > jointsPtr;
typedef boost::shared_ptr< ::ex2_pkg_msgs::joints const> jointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ex2_pkg_msgs::joints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ex2_pkg_msgs::joints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ex2_pkg_msgs::joints_<ContainerAllocator1> & lhs, const ::ex2_pkg_msgs::joints_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ex2_pkg_msgs::joints_<ContainerAllocator1> & lhs, const ::ex2_pkg_msgs::joints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ex2_pkg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ex2_pkg_msgs::joints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ex2_pkg_msgs::joints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex2_pkg_msgs::joints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex2_pkg_msgs::joints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex2_pkg_msgs::joints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex2_pkg_msgs::joints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ex2_pkg_msgs::joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03d6253bad558f8093b6baf0e2461947";
  }

  static const char* value(const ::ex2_pkg_msgs::joints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03d6253bad558f80ULL;
  static const uint64_t static_value2 = 0x93b6baf0e2461947ULL;
};

template<class ContainerAllocator>
struct DataType< ::ex2_pkg_msgs::joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ex2_pkg_msgs/joints";
  }

  static const char* value(const ::ex2_pkg_msgs::joints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ex2_pkg_msgs::joints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "position[] positions\n"
"================================================================================\n"
"MSG: ex2_pkg_msgs/position\n"
"uint8 position\n"
;
  }

  static const char* value(const ::ex2_pkg_msgs::joints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ex2_pkg_msgs::joints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ex2_pkg_msgs::joints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ex2_pkg_msgs::joints_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ex2_pkg_msgs::position_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EX2_PKG_MSGS_MESSAGE_JOINTS_H
