// Generated by gencpp from file ex2_pkg_msgs/position.msg
// DO NOT EDIT!


#ifndef EX2_PKG_MSGS_MESSAGE_POSITION_H
#define EX2_PKG_MSGS_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ex2_pkg_msgs
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : position(0)  {
    }
  position_(const ContainerAllocator& _alloc)
    : position(0)  {
  (void)_alloc;
    }



   typedef uint8_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::ex2_pkg_msgs::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ex2_pkg_msgs::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::ex2_pkg_msgs::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::ex2_pkg_msgs::position > positionPtr;
typedef boost::shared_ptr< ::ex2_pkg_msgs::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ex2_pkg_msgs::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ex2_pkg_msgs::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ex2_pkg_msgs::position_<ContainerAllocator1> & lhs, const ::ex2_pkg_msgs::position_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ex2_pkg_msgs::position_<ContainerAllocator1> & lhs, const ::ex2_pkg_msgs::position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ex2_pkg_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ex2_pkg_msgs::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ex2_pkg_msgs::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex2_pkg_msgs::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex2_pkg_msgs::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex2_pkg_msgs::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex2_pkg_msgs::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ex2_pkg_msgs::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dd1aa2cda989887d566114cab493168";
  }

  static const char* value(const ::ex2_pkg_msgs::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dd1aa2cda989887ULL;
  static const uint64_t static_value2 = 0xd566114cab493168ULL;
};

template<class ContainerAllocator>
struct DataType< ::ex2_pkg_msgs::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ex2_pkg_msgs/position";
  }

  static const char* value(const ::ex2_pkg_msgs::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ex2_pkg_msgs::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 position\n"
;
  }

  static const char* value(const ::ex2_pkg_msgs::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ex2_pkg_msgs::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ex2_pkg_msgs::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ex2_pkg_msgs::position_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EX2_PKG_MSGS_MESSAGE_POSITION_H
