// Auto-generated. Do not edit!

// (in-package kinematics_action_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class GetIKSolutionsGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.end_effector_pose = null;
    }
    else {
      if (initObj.hasOwnProperty('end_effector_pose')) {
        this.end_effector_pose = initObj.end_effector_pose
      }
      else {
        this.end_effector_pose = new geometry_msgs.msg.Pose();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GetIKSolutionsGoal
    // Serialize message field [end_effector_pose]
    bufferOffset = geometry_msgs.msg.Pose.serialize(obj.end_effector_pose, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GetIKSolutionsGoal
    let len;
    let data = new GetIKSolutionsGoal(null);
    // Deserialize message field [end_effector_pose]
    data.end_effector_pose = geometry_msgs.msg.Pose.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 56;
  }

  static datatype() {
    // Returns string type for a message object
    return 'kinematics_action_msgs/GetIKSolutionsGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9be2bcfd9d56e8cd78063c8b79e875d0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/Pose end_effector_pose
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GetIKSolutionsGoal(null);
    if (msg.end_effector_pose !== undefined) {
      resolved.end_effector_pose = geometry_msgs.msg.Pose.Resolve(msg.end_effector_pose)
    }
    else {
      resolved.end_effector_pose = new geometry_msgs.msg.Pose()
    }

    return resolved;
    }
};

module.exports = GetIKSolutionsGoal;
