controller_list:
  - name: fake_fanuc_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses.
  - group: fanuc_arm
    pose: home