(cl:defpackage kinematics_action_msgs-msg
  (:use )
  (:export
   "<GETIKSOLUTIONSACTION>"
   "GETIKSOLUTIONSACTION"
   "<GETIKSOLUTIONSACTIONFEEDBACK>"
   "GETIKSOLUTIONSACTIONFEEDBACK"
   "<GETIKSOLUTIONSACTIONGOAL>"
   "GETIKSOLUTIONSACTIONGOAL"
   "<GETIKSOLUTIONSACTIONRESULT>"
   "GETIKSOLUTIONSACTIONRESULT"
   "<GETIKSOLUTIONSFEEDBACK>"
   "GETIKSOLUTIONSFEEDBACK"
   "<GETIKSOLUTIONSGOAL>"
   "GETIKSOLUTIONSGOAL"
   "<GETIKSOLUTIONSRESULT>"
   "GETIKSOLUTIONSRESULT"
  ))

