; Auto-generated. Do not edit!


(cl:in-package kinematics_action_msgs-msg)


;//! \htmlinclude GetIKSolutionsGoal.msg.html

(cl:defclass <GetIKSolutionsGoal> (roslisp-msg-protocol:ros-message)
  ((end_effector_pose
    :reader end_effector_pose
    :initarg :end_effector_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass GetIKSolutionsGoal (<GetIKSolutionsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GetIKSolutionsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GetIKSolutionsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kinematics_action_msgs-msg:<GetIKSolutionsGoal> is deprecated: use kinematics_action_msgs-msg:GetIKSolutionsGoal instead.")))

(cl:ensure-generic-function 'end_effector_pose-val :lambda-list '(m))
(cl:defmethod end_effector_pose-val ((m <GetIKSolutionsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kinematics_action_msgs-msg:end_effector_pose-val is deprecated.  Use kinematics_action_msgs-msg:end_effector_pose instead.")
  (end_effector_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GetIKSolutionsGoal>) ostream)
  "Serializes a message object of type '<GetIKSolutionsGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'end_effector_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GetIKSolutionsGoal>) istream)
  "Deserializes a message object of type '<GetIKSolutionsGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'end_effector_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GetIKSolutionsGoal>)))
  "Returns string type for a message object of type '<GetIKSolutionsGoal>"
  "kinematics_action_msgs/GetIKSolutionsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GetIKSolutionsGoal)))
  "Returns string type for a message object of type 'GetIKSolutionsGoal"
  "kinematics_action_msgs/GetIKSolutionsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GetIKSolutionsGoal>)))
  "Returns md5sum for a message object of type '<GetIKSolutionsGoal>"
  "9be2bcfd9d56e8cd78063c8b79e875d0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GetIKSolutionsGoal)))
  "Returns md5sum for a message object of type 'GetIKSolutionsGoal"
  "9be2bcfd9d56e8cd78063c8b79e875d0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GetIKSolutionsGoal>)))
  "Returns full string definition for message of type '<GetIKSolutionsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose end_effector_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GetIKSolutionsGoal)))
  "Returns full string definition for message of type 'GetIKSolutionsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose end_effector_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GetIKSolutionsGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'end_effector_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GetIKSolutionsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GetIKSolutionsGoal
    (cl:cons ':end_effector_pose (end_effector_pose msg))
))
